---
tasks:

  - name: Install utility packages
    apt:
      name: "{{ item }}"
    with_items: utility_packages

  - name: Install image optimization packages
    apt:
      name: "{{ item }}"
    with_items: image_optimization_packages
    when: install_image_optimization_packages
